/* Copyright (c) 2011, 2012, Oracle and/or its affiliates. All rights reserved. */
/* ------------------------------------------------------ */
/* ------------------- ADFInfoBundle_pt_BR.js ---------------------- */
/* ------------------------------------------------------ */
// AUTO-GENERATED FILE
// since this gets loaded programmatically, adf.mf.resource will already be defined

adf.mf.resource.ADFInfoBundle_pt_BR={
"MSG_ATTEMPT_TO_GO_NEGATIVE_NESTING":"Tentando ficar negativo no n\u221a\u2260vel de aninhamento para {0} {1}",
"MSG_LOGIN_TENANT_NAME":"Nome do Tenant",
"MSG_LOGIN_PASSWORD":"Senha",
"MSG_LOGIN_USERNAME":"Nome do usu\u221a\u00b0rio",
"MSG_LOGIN_WELCOME":"Bem-vindo",
"MSG_ERROR_IN_SCRIPT":"Erro de Javascript no est\u221a\u00b0gio {0}. Erro: {1}",
"MSG_ERROR_IN_LOGOUT":"Erro ao tentar efetuar log-out. Erro: {0}",
"oracle.core.ojdl.logging.MessageIdKeyResourceBundle":"",
"MSG_ERROR_IN_LOGIN":"Erro ao tentar efetuar log-in. Erro: {0}",
"MSG_ERROR_REGISTER_ACTIVATION_HANDLER":"Erro ao registrar o handler de ativa\u221a\u00df\u221a\u00a3o. C\u221a\u2265digo de erro: {0}",
"MSG_LOGIN_TENANT_ID":"ID do Tenant",
"MSG_ERROR_TREENODEITERATOR_UPDATE_KEYS":"ocorreu um problema ao atualizar {0} chaves - {1}",
"MSG_ERROR_MNGD_BEANS_NOT_SUPPORTED":"N\u221a\u00a3o s\u221a\u00a3o suportados beans gerenciados em um ambiente com base n\u221a\u00a3o-java.",
"MSG_UNABLE_TO_FETCH_SET":"n\u221a\u00a3o \u221a\u00a9 poss\u221a\u2260vel extrair o conjunto - {0}",
"MSG_ERROR_TREENODEITERATOR_UPDATE_PROVIDERS":"n\u221a\u00a3o \u221a\u00a9 poss\u221a\u2260vel atualizar o provedor porque o cm \u221a\u00a9 indefinido.",
"MSG_ERROR_NOTIFYING_DATA_CHANGE_LISTENER":"Advert\u221a\u2122ncia: ocorreu um problema ao notificar escutas de altera\u221a\u00df\u221a\u00a3o de dados para {0}",
"MSG_ERROR_PROCESSING_PROVIDER_CHANGES":"Erro em processDataChangeEvent ao processar as altera\u221a\u00df\u221a\u00b5es {0} do provedor",
"MSG_ERROR_PURGING_CACHE":"ERRO: ao tentar expurgar o cache - {0}",
"MSG_ERROR_UPDATING_CACHE":"Advert\u221a\u2122ncia: ocorreu um problema ao atualizar o cache como resultado de um evento de altera\u221a\u00df\u221a\u00a3o de dados.",
"MSG_ADFMOBILE_NOT_FOUND":"ADVERT\u221a\u00e4NCIA: falha do adfmf no seguinte comando {0}:{1} porque n\u221a\u00a3o foi poss\u221a\u2260vel encontrar a classe ADFMobile.",
"MSG_QUERY_PARAMETER_NOT_FOUND":"O par\u221a\u00a2metro de consulta \'\'{0}\'\' n\u221a\u00a3o foi encontrado.",
"MSG_EL_PARSER_UNEXPECTED_UNIARY_OP_FOUND":"unexpected (unary) operation found",
"MSG_EL_PARSER_UNEXPECTED_BINARY_OP_FOUND":"unexpected (binary) operation found",
"MSG_EL_PARSER_NESTED_EL_NOT_SUPPORTED":"nested EL Expressions are not supported.",
"MSG_EL_PARSER_UNEXPECTED_OPERATOR_FOUND":"unexpected operator found",
"MSG_EL_PARSER_UNEXPECTED_TERNARY_OP_FOUND":"unexpected (ternary) operation found",
"MSG_ERROR_IN_ERROR_CALLBACK":"Erro encontrado ao chamar o callback de erro",
"MSG_ERROR_IN_INDIVIDUAL_NOTIFICATION_CALLBACK":"Foi encontrado um erro ao chamar o callback de notifica\u221a\u00df\u221a\u00a3o de altera\u221a\u00df\u221a\u00a3o de dados para {0}. Erro: {1}",
"MSG_ERROR_IN_BULK_NOTIFICATION_CALLBACK":"Foi encontrado um erro ao chamar o callback de notifica\u221a\u00df\u221a\u00a3o de altera\u221a\u00df\u221a\u00a3o de dados de alto volume. Erro: {0}",
"MSG_ERROR_PROCESSING_VAR_CHANGES":"Erro em processDataChangeEvent ao processar as altera\u221a\u00df\u221a\u00b5es {0} da vari\u221a\u00b0vel",
"MSG_EL_PARSER_UNEXPECTED_STRING_FOUND":"unexpected string constant found",
"MSG_SET_LOCAL_VALUE_FAILED":"falha na defini\u221a\u00df\u221a\u00a3o do valor local; agora chamando o(s) callback(s) de falha sobre {0}",
"MSG_EL_PARSER_UNEXPECTED_VARIABLE_FOUND":"unexpected variable found",
"MSG_ERROR_RESETTING_BINDING_CONTEXT":"Erro ao redefinir o contexto de vincula\u221a\u00df\u221a\u00a3o. - {0}",
"MSG_ERROR_CALLING_ERROR_HANDLERS":"Erro encontrado ao chamar os handlers de erro. - {0}",
"MSG_EL_PARSER_UNEXPECTED_NUMBER_CONSTANT_FOUND":"unexpected number constant found",
"MSG_ERROR_PROCESSING_REMOVE_DATA_CHANGE":"Advert\u221a\u2122ncia: ocorreu um problema ao processar a altera\u221a\u00df\u221a\u00a3o de dados (remo\u221a\u00df\u221a\u00a3o) para #\'{{0}.collectionModel\'} - {1}",
"MSG_ERROR_PROCESSING_CREATE_DATA_CHANGE":"Advert\u221a\u2122ncia: ocorreu um problema ao processar a altera\u221a\u00df\u221a\u00a3o de dados (cria\u221a\u00df\u221a\u00a3o) para #\'{{0}.collectionModel\'} - {1}",
"MSG_ERROR_PROCESSING_UPDATE_DATA_CHANGE":"Advert\u221a\u2122ncia: ocorreu um problema ao processar a altera\u221a\u00df\u221a\u00a3o de dados (atualiza\u221a\u00df\u221a\u00a3o) para #\'{{0}.collectionModel\'} - {1}",
"MSG_LOGIN_WARNING":"Erro: informe o nome de usu\u221a\u00b0rio e a senha.",
"MSG_ERROR_IN_EL_PARSING":"EL Parsing Error: {0} -- [column {1}] {2}",
"MSG_EL_PARSER_UNABLE_TO_RESOLVE":"Unable to resolve {0} with the given variables: ",
"MSG_EL_PARSER_INCORRECT_OPERANDS":"incorrect number of operands {0} - {1}",
"MSG_EL_PARSER_MISMATCH":"non-matching () or []",
"MSG_EL_PARSER_MISSING_ENDING":"no ending expression marker found",
"MSG_EL_PARSER_UNKNOWN_CHAR_FOUND":"unknown character \'{0}\' found.",
"MSG_EL_PARSER_UNEXPECTED_CONSTANT_FOUND":"unexpected constant found",
"MSG_ERROR_IN_REQUEST":"Erro: solicita\u221a\u00df\u221a\u00a3o: {0} exce\u221a\u00df\u221a\u00a3o: {1}",
"MSG_SKIP_REMOTE_WRITE":"J\u221a\u00b0 que java n\u221a\u00a3o est\u221a\u00b0 dispon\u221a\u2260vel, ignoraremos a grava\u221a\u00df\u221a\u00a3o remota.",
"MSG_GETVALUE_FAILED_CB_ERROR":"falha ao obter valor {0}th erro de callback - {1}",
"MSG_GETVALUE_SUCCESS_CB_ERROR":"sucesso ao obter valor de {0}th erro de callback - {1}",
"MSG_LOGIN_LOGIN_BUTTON_LABEL":"Efetuar Log-in",
"MSG_EXCEPTION":"Exce\u221a\u00df\u221a\u00a3o: {0}",
"MSG_LOGIN_EXIT_BUTTON_LABEL":"Sair da Aplica\u221a\u00df\u221a\u00a3o",
"MSG_EXCEPTION_RESOLVING":"Exce\u221a\u00df\u221a\u00a3o {0} ao tentar resolver {1}",
"MSG_SET_LOCAL_VALUE_FAILED_CB":"um callback de falha de defini\u221a\u00df\u221a\u00a3o de valor local foi executado, mas lan\u221a\u00dfa - {0}",
"MSG_SET_LOCAL_VALUE_SUCCESS_CB_FAILED":"um callback {0}th de sucesso de defini\u221a\u00df\u221a\u00a3o de valor local falhou com a exce\u221a\u00df\u221a\u00a3o {1}",
"MSG_ERROR_PROCESSING_DATA_CHANGE_EVENT":"erro ao processar o evento de altera\u221a\u00df\u221a\u00a3o de dados - {0}",
"MSG_UNABLE_TO_SET_DATA_CHANGE_VALS":"ERRO: n\u221a\u00a3o \u221a\u00a9 poss\u221a\u2260vel definir valores [{0}] de eventos de altera\u221a\u00df\u221a\u00a3o de dados"
}
